[colors]
[colors.primary]
background = "#003642"
foreground = "#ffffff"

[colors.normal]
black   = "#003642"
red     = "#ca665e"
green   = "#a3cc6b"
yellow  = "#c6c380"
blue    = "#9aafbc"
magenta = "#c3a2ac"
cyan    = "#5DC8CD"
white   = "#E4ECE6"

[colors.bright]
black   = "#414e2b"
red     = "#e4a5a0"
green   = "#cee6ad"
yellow  = "#e4e3be"
blue    = "#d0dbe1"
magenta = "#e8d9de"
cyan    = "#a0e3e6"
white   = "#ffffff"

[colors.cursor]
text   = "#003642"
cursor = "#ffffff"
