accent = "#9aafbc"
cursor = "#ffffff"
foreground = "#ffffff"
background = "#003642"
selection_foreground = "#ffffff"
selection_background = "#9aafbc"

color0 = "#003642"
color1 = "#ca665e"
color2 = "#a3cc6b"
color3 = "#c6c380"
color4 = "#9aafbc"
color5 = "#c3a2ac"
color6 = "#5DC8CD"
color7 = "#E4ECE6"
color8 = "#414e2b"
color9 = "#e4a5a0"
color10 = "#cee6ad"
color11 = "#e4e3be"
color12 = "#d0dbe1"
color13 = "#e8d9de"
color14 = "#a0e3e6"
color15 = "#ffffff"
